usuarios = {
    "tecnologiaw": {
        "nome": "Tecnologia da Informação",
        "senha": "PwTi@11Stw16",
        "acesso": [
            "Vendas_Janeiro_Campinas",
            "Vendas_Janeiro_Higienopolis",
            "Vendas_Janeiro_JK",
            "Vendas_Janeiro_Rebouças",
            "Vendas_Janeiro_Ribeirão",
            "Vendas_Fevereiro_Campinas",
            "Vendas_Fevereiro_Higienopolis",
            "Vendas_Fevereiro_JK",
            "Vendas_Fevereiro_Rebouças",
            "Vendas_Fevereiro_Ribeirão",
            "Vendas_Março_Campinas",
            "Vendas_Março_Higienopolis",
            "Vendas_Março_JK",
            "Vendas_Março_Rebouças",
            "Vendas_Março_Ribeirão",
            "Vendas_Abril_Campinas",
            "Vendas_Abril_Higienopolis",
            "Vendas_Abril_JK",
            "Vendas_Abril_Rebouças",
            "Vendas_Abril_Ribeirão",
            "Vendas_Maio_Campinas",
            "Vendas_Maio_Higienopolis",
            "Vendas_Maio_JK",
            "Vendas_Maio_Rebouças",
            "Vendas_Maio_Ribeirão",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu",
            "Campanha_Davines_Rede"
        ]
    },
    "greboucas": {
        "nome": "Gerência Rebouças",
        "senha": "PwbiRb@1808",
        "acesso": [
            "Vendas_Janeiro_Rebouças",
            "Vendas_Fevereiro_Rebouças",
            "Vendas_Março_Rebouças",
            "Vendas_Abril_Rebouças",
            "Vendas_Maio_Rebouças",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Rebouças",
            "Campanha_Davines_Geral_Sem_Pontuação"


        ]
    },
    "ghigi": {
        "nome": "Gerência Higienópolis",
        "senha": "PwbiHg@1809",
        "acesso": [
            "Vendas_Janeiro_Higienopolis",
            "Vendas_Fevereiro_Higienopolis",
            "Vendas_Março_Higienopolis",
            "Vendas_Abril_Higienopolis",
            "Vendas_Maio_Higienopolis",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Higienopolis",
            "Campanha_Davines_Geral_Sem_Pontuação"
        ]
    },
    "gjk": {
        "nome": "Gerência JK",
        "senha": "PwbiJk@1811",
        "acesso": [
            "Vendas_Janeiro_JK",
            "Vendas_Fevereiro_JK",
            "Vendas_Março_JK",
            "Vendas_Abril_JK",
            "Vendas_Maio_JK",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_JK",
            "Campanha_Davines_Geral_Sem_Pontuação"
        ]
    },
    "gritu": {
        "nome": "Gerência Ritu",
        "senha": "PwbiRitu@1812",
        "acesso": [
            "Campanha_Davines_Ritu"
        ]
    },
    "gcampinas": {
        "nome": "Gerência Campinas",
        "senha": "PwbiCamp@1813",
        "acesso": [
            "Vendas_Janeiro_Campinas",
            "Vendas_Fevereiro_Campinas",
            "Vendas_Março_Campinas",
            "Vendas_Abril_Campinas",
            "Vendas_Maio_Campinas",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Geral_Sem_Pontuação"
        ]
    },
    "gribeirao": {
        "nome": "Gerência Ribeirão",
        "senha": "PwbiRib@1813",
        "acesso": [
            "Vendas_Janeiro_Ribeirão",
            "Vendas_Fevereiro_Ribeirão",
            "Vendas_Março_Ribeirão",
            "Vendas_Abril_Ribeirão",
            "Vendas_Maio_Ribeirão",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ribeirão",
            "Campanha_Davines_Geral_Sem_Pontuação"
           
        ]
    },
    "hnavarini": {
        "nome": "Herbert Navarini",
        "senha": "Hnavarini@1815",
        "acesso": [
            "Vendas_Janeiro_Campinas",
            "Vendas_Janeiro_Higienopolis",
            "Vendas_Janeiro_JK",
            "Vendas_Janeiro_Rebouças",
            "Vendas_Janeiro_Ribeirão",
            "Vendas_Fevereiro_Campinas",
            "Vendas_Fevereiro_Higienopolis",
            "Vendas_Fevereiro_JK",
            "Vendas_Fevereiro_Rebouças",
            "Vendas_Fevereiro_Ribeirão",
            "Vendas_Março_Campinas",
            "Vendas_Março_Higienopolis",
            "Vendas_Março_JK",
            "Vendas_Março_Rebouças",
            "Vendas_Março_Ribeirão",
            "Vendas_Abril_Campinas",
            "Vendas_Abril_Higienopolis",
            "Vendas_Abril_JK",
            "Vendas_Abril_Rebouças",
            "Vendas_Abril_Ribeirão",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu"
        ]
    },
    "comercialw": {
        "nome": "Comercial Studio W",
        "senha": "@!Comercial2108",
        "acesso": [
            "Vendas_Janeiro_Campinas",
            "Vendas_Janeiro_Higienopolis",
            "Vendas_Janeiro_JK",
            "Vendas_Janeiro_Rebouças",
            "Vendas_Janeiro_Ribeirão",
            "Vendas_Fevereiro_Campinas",
            "Vendas_Fevereiro_Higienopolis",
            "Vendas_Fevereiro_JK",
            "Vendas_Fevereiro_Rebouças",
            "Vendas_Fevereiro_Ribeirão",
            "Vendas_Março_Campinas",
            "Vendas_Março_Higienopolis",
            "Vendas_Março_JK",
            "Vendas_Março_Rebouças",
            "Vendas_Março_Ribeirão",
            "Vendas_Abril_Campinas",
            "Vendas_Abril_Higienopolis",
            "Vendas_Abril_JK",
            "Vendas_Abril_Rebouças",
            "Vendas_Abril_Ribeirão",
            "Vendas_Maio_Campinas",
            "Vendas_Maio_Higienopolis",
            "Vendas_Maio_JK",
            "Vendas_Maio_Rebouças",
            "Vendas_Maio_Ribeirão",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu",
            "Campanha_Davines_Rede"
        ]
    },
    "financeirow": {
        "nome": "Financeiro Studio W",
        "senha": "@!Financeiro0821",
        "acesso": [
            "Vendas_Janeiro_Campinas",
            "Vendas_Janeiro_Higienopolis",
            "Vendas_Janeiro_JK",
            "Vendas_Janeiro_Rebouças",
            "Vendas_Janeiro_Ribeirão",
            "Vendas_Fevereiro_Campinas",
            "Vendas_Fevereiro_Higienopolis",
            "Vendas_Fevereiro_JK",
            "Vendas_Fevereiro_Rebouças",
            "Vendas_Fevereiro_Ribeirão",
            "Vendas_Março_Campinas",
            "Vendas_Março_Higienopolis",
            "Vendas_Março_JK",
            "Vendas_Março_Rebouças",
            "Vendas_Março_Ribeirão",
            "Vendas_Abril_Campinas",
            "Vendas_Abril_Higienopolis",
            "Vendas_Abril_JK",
            "Vendas_Abril_Rebouças",
            "Vendas_Abril_Ribeirão",
            "Vendas_Maio_Campinas",
            "Vendas_Maio_Higienopolis",
            "Vendas_Maio_JK",
            "Vendas_Maio_Rebouças",
            "Vendas_Maio_Ribeirão",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu"
        ]
    },
    "rosangelab": {
        "nome": "Rosângela Barchetta",
        "senha": "@!Diretoria1005",
        "acesso": [
            "Vendas_Janeiro_Campinas",
            "Vendas_Janeiro_Higienopolis",
            "Vendas_Janeiro_JK",
            "Vendas_Janeiro_Rebouças",
            "Vendas_Janeiro_Ribeirão",
            "Vendas_Fevereiro_Campinas",
            "Vendas_Fevereiro_Higienopolis",
            "Vendas_Fevereiro_JK",
            "Vendas_Fevereiro_Rebouças",
            "Vendas_Fevereiro_Ribeirão",
            "Vendas_Março_Campinas",
            "Vendas_Março_Higienopolis",
            "Vendas_Março_JK",
            "Vendas_Março_Rebouças",
            "Vendas_Março_Ribeirão",
            "Vendas_Abril_Campinas",
            "Vendas_Abril_Higienopolis",
            "Vendas_Abril_JK",
            "Vendas_Abril_Rebouças",
            "Vendas_Abril_Ribeirão",
            "Vendas_Maio_Campinas",
            "Vendas_Maio_Higienopolis",
            "Vendas_Maio_JK",
            "Vendas_Maio_Rebouças",
            "Vendas_Maio_Ribeirão",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu"
        ]
    },
        "academiacrm": {
        "nome": "Academia CRM",
        "senha": "$oD2E44T",
        "acesso": [
            "Vendas_Janeiro_Campinas",
            "Vendas_Janeiro_Higienopolis",
            "Vendas_Janeiro_JK",
            "Vendas_Janeiro_Rebouças",
            "Vendas_Janeiro_Ribeirão",
            "Vendas_Fevereiro_Campinas",
            "Vendas_Fevereiro_Higienopolis",
            "Vendas_Fevereiro_JK",
            "Vendas_Fevereiro_Rebouças",
            "Vendas_Fevereiro_Ribeirão",
            "Vendas_Março_Campinas",
            "Vendas_Março_Higienopolis",
            "Vendas_Março_JK",
            "Vendas_Março_Rebouças",
            "Vendas_Março_Ribeirão",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu"
        ]
    },
}