usuarios = {
    "tecnologiaw": {
        "nome": "Tecnologia da Informação",
        "senha": "PwTi@11Stw16",
        "acesso": [
            "Vendas_Novembro_Campinas",
            "Vendas_Novembro_Ribeirao",
            "Vendas_Novembro_Reboucas",
            "Vendas_Novembro_Higienopolis",
            "Vendas_Novembro_JK",
            "Vendas_Julho_Reboucas",
            "Vendas_Agosto_Reboucas",
            "Vendas_Setembro_Reboucas",
            "Vendas_Dezembro_Campinas",
            "Vendas_Dezembro_Ribeirao",
            "Vendas_Dezembro_Reboucas",
            "Vendas_Dezembro_Higienopolis",
            "Vendas_Dezembro_JK",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu"
        ]
    },
    "greboucas": {
        "nome": "Gerência Rebouças",
        "senha": "PwbiRb@1808",
        "acesso": [
            "Vendas_Novembro_Reboucas",
            "Vendas_Agosto_Reboucas",
            "Vendas_Setembro_Reboucas",
            "Vendas_Julho_Reboucas",
            "Vendas_Dezembro_Reboucas",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração"


        ]
    },
    "ghigi": {
        "nome": "Gerência Higienópolis",
        "senha": "PwbiHg@1809",
        "acesso": [
            "Vendas_Novembro_Higienopolis",
            "Vendas_Dezembro_Higienopolis",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração"
        ]
    },
    "gjk": {
        "nome": "Gerência JK",
        "senha": "PwbiJk@1811",
        "acesso": [
            "Vendas_Novembro_JK",
            "Vendas_Dezembro_JK",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração"
        ]
    },
    "gritu": {
        "nome": "Gerência Ritu",
        "senha": "PwbiRitu@1812",
        "acesso": [
            "Campanha_Davines_Ritu"
        ]
    },
    "gcampinas": {
        "nome": "Gerência Campinas",
        "senha": "PwbiCamp@1813",
        "acesso": [
            "Vendas_Novembro_Campinas"
            "Vendas_Dezembro_Campinas",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração"
        ]
    },
    "gribeirao": {
        "nome": "Gerência Ribeirão",
        "senha": "PwbiRib@1813",
        "acesso": [
            "Vendas_Novembro_Ribeirao",
            "Vendas_Dezembro_Ribeirao",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração"
           
        ]
    },
    "hnavarini": {
        "nome": "Herbert Navarini",
        "senha": "Hnavarini@1815",
        "acesso": [
            "Vendas_Novembro_Campinas",
            "Vendas_Novembro_Ribeirao",
            "Vendas_Novembro_Reboucas",
            "Vendas_Novembro_Higienopolis",
            "Vendas_Novembro_JK",
            "Vendas_Julho_Reboucas",
            "Vendas_Agosto_Reboucas",
            "Vendas_Setembro_Reboucas",
            "Vendas_Dezembro_Campinas",
            "Vendas_Dezembro_Ribeirao",
            "Vendas_Dezembro_Reboucas",
            "Vendas_Dezembro_Higienopolis",
            "Vendas_Dezembro_JK",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu"
        ]
    },
    "comercialw": {
        "nome": "Comercial Studio W",
        "senha": "@!Comercial2108",
        "acesso": [
            "Vendas_Novembro_Campinas",
            "Vendas_Novembro_Ribeirao",
            "Vendas_Novembro_Reboucas",
            "Vendas_Novembro_Higienopolis",
            "Vendas_Novembro_JK",
            "Vendas_Julho_Reboucas",
            "Vendas_Agosto_Reboucas",
            "Vendas_Setembro_Reboucas",
            "Vendas_Dezembro_Campinas",
            "Vendas_Dezembro_Ribeirao",
            "Vendas_Dezembro_Reboucas",
            "Vendas_Dezembro_Higienopolis",
            "Vendas_Dezembro_JK",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu"
        ]
    },
    "financeirow": {
        "nome": "Financeiro Studio W",
        "senha": "@!Financeiro0821",
        "acesso": [
            "Vendas_Novembro_Campinas",
            "Vendas_Novembro_Ribeirao",
            "Vendas_Novembro_Reboucas",
            "Vendas_Novembro_Higienopolis",
            "Vendas_Novembro_JK",
            "Vendas_Julho_Reboucas",
            "Vendas_Agosto_Reboucas",
            "Vendas_Setembro_Reboucas",
            "Vendas_Dezembro_Campinas",
            "Vendas_Dezembro_Ribeirao",
            "Vendas_Dezembro_Reboucas",
            "Vendas_Dezembro_Higienopolis",
            "Vendas_Dezembro_JK",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu"
        ]
    },
    "rosangelab": {
        "nome": "Rosângela Barchetta",
        "senha": "@!Diretoria1005",
        "acesso": [
            "Vendas_Novembro_Campinas",
            "Vendas_Novembro_Ribeirao",
            "Vendas_Novembro_Reboucas",
            "Vendas_Novembro_Higienopolis",
            "Vendas_Novembro_JK",
            "Vendas_Julho_Reboucas",
            "Vendas_Agosto_Reboucas",
            "Vendas_Setembro_Reboucas",
            "Vendas_Dezembro_Campinas",
            "Vendas_Dezembro_Ribeirao",
            "Vendas_Dezembro_Reboucas",
            "Vendas_Dezembro_Higienopolis",
            "Vendas_Dezembro_JK",
            "Campanha_Gerentes_Wella_Campinas",
            "Campanha_Gerentes_Wella_Ribeirao",
            "Campanha_Gerentes_Wella_Reboucas",
            "Campanha_Gerentes_Wella_Higienopolis",
            "Campanha_Gerentes_Wella_JK",
            "Campanha_Gerentes_Loreal_Campinas",
            "Campanha_Gerentes_Loreal_Ribeirao",
            "Campanha_Gerentes_Loreal_Reboucas",
            "Campanha_Gerentes_Loreal_Higienopolis",
            "Campanha_Gerentes_Loreal_JK",
            "Campanha_Loreal_Coloração",
            "Campanha_Loreal_Assistentes_Novembro",
            "Campanha_Loreal_Assistentes_Dezembro",
            "Campanha_Wella_Assistentes_Dezembro",
            "Campanha_Loreal_Tratamento_Dezembro",
            "Campanha_Wella_Tratamento_Dezembro",
            "Campanha_Wella_Coloração",
            "Campanha_Davines_Ritu"
        ]
    }
}